version: '3.2'
services:
  database:
    image: postgres:15.4
    env_file:
      - database.env
    ports:
      - "6543:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  keycloak:
    image: keycloak/keycloak:24.0.4
    env_file:
      - keycloak.env
    ports:
      - "8080:8080"
    command: start-dev

  python-app:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - keycloak

  react-app:
    build: ./frontend
    ports:
      - "3000:3000"
      - "80:3000"
    depends_on:
      - keycloak

volumes:
  database-data: # named volumes can be managed easier using docker-compose